# Generated by Django 4.1.7 on 2023-02-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('program', models.CharField(max_length=200, verbose_name='Programa')),
                ('user', models.CharField(max_length=200, verbose_name='Usuario')),
                ('password', models.CharField(max_length=200, verbose_name='Contraseña')),
                ('image', models.ImageField(upload_to='projects', verbose_name='Foto de perfil')),
                ('category', models.CharField(choices=[('P', 'Pregrado'), ('G', 'Postgrado'), ('A', 'Ambos'), ('D', 'Administrativos'), ('T', 'Todos')], max_length=200, null=True, verbose_name='Categoría')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created'],
            },
        ),
    ]
