# Generated by Django 4.2.1 on 2023-06-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineaAmiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Título')),
                ('content', models.TextField(null=True, verbose_name='Contenido')),
                ('image', models.ImageField(null=True, upload_to='linea amiga', verbose_name='Imagen')),
                ('question1', models.CharField(max_length=200, null=True, verbose_name='Pregunta 1')),
                ('question2', models.CharField(max_length=200, null=True, verbose_name='Pregunta 2')),
                ('question3', models.CharField(max_length=200, null=True, verbose_name='Pregunta 3')),
                ('question4', models.CharField(max_length=200, null=True, verbose_name='Pregunta 4')),
                ('link_date', models.URLField(null=True, verbose_name='Link agendar cita')),
                ('link_FQ', models.URLField(null=True, verbose_name='Link preguntas frecuentes')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
            },
        ),
    ]
